/**
 * Sports & Activities Metadata for Santrino Marketplace
 */

export const ACTIVITIES = [
  {
    id: 'padel',
    name: 'بادل',
    nameEn: 'Padel',
    icon: '🎾',
    badgeColor: '#0D6B4F',
    defaultBookingType: 'time_slot',
    defaultDuration: 90,
    unitName: 'ملعب',
    description: 'ملاعب بادل بانورامية ومغطاة احترافية مع أرضيات WPT ومضارب متوفرة',
    popular: true,
  },
  {
    id: 'football',
    name: 'كرة القدم',
    nameEn: 'Football',
    icon: '⚽',
    badgeColor: '#1B8055',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'ملعب',
    description: 'ملاعب خماسية وسباعية وقانونية مع نجيل تركي ممتاز وإضاءة ليلية HD',
    popular: true,
  },
  {
    id: 'tennis',
    name: 'تنس أرضي',
    nameEn: 'Tennis',
    icon: '🎾',
    badgeColor: '#B8860B',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'ملعب',
    description: 'ملاعب صلبة وترابية بمواصفات دولية للتدريب والمباريات',
    popular: true,
  },
  {
    id: 'swimming',
    name: 'سباحة وحصص مائية',
    nameEn: 'Swimming',
    icon: '🏊',
    badgeColor: '#0284C7',
    defaultBookingType: 'session',
    defaultDuration: 60,
    unitName: 'جلسة / فرد',
    description: 'مسابح أولمبية ونصف أولمبية مدفأة مع حارات سباحة حرة ومدربين معتمدين',
    popular: true,
  },
  {
    id: 'basketball',
    name: 'كرة السلة',
    nameEn: 'Basketball',
    icon: '🏀',
    badgeColor: '#EA580C',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'صالة / ملعب',
    description: 'صالات باركيه مغطاة وملاعب خارجية مع أطواق رسمية',
    popular: true,
  },
  {
    id: 'volleyball',
    name: 'كرة الطائرة',
    nameEn: 'Volleyball',
    icon: '🏐',
    badgeColor: '#9333EA',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'ملعب',
    description: 'صالات مغطاة وملاعب طائرة شاطئية',
    popular: false,
  },
  {
    id: 'badminton',
    name: 'ريشة طائرة',
    nameEn: 'Badminton',
    icon: '🏸',
    badgeColor: '#16A34A',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'ملعب',
    description: 'ملاعب ريشة داخلية مجهزة ومضاءة',
    popular: false,
  },
  {
    id: 'table_tennis',
    name: 'تنس طاولة',
    nameEn: 'Table Tennis',
    icon: '🏓',
    badgeColor: '#DC2626',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'طاولة',
    description: 'طاولات احترافية مع مضارب وكرات لجميع المستويات',
    popular: false,
  },
  {
    id: 'fitness',
    name: 'لياقة وجيم',
    nameEn: 'Fitness & Gym',
    icon: '🏋️',
    badgeColor: '#4F46E5',
    defaultBookingType: 'session',
    defaultDuration: 60,
    unitName: 'تذكرة / حصة',
    description: 'حصص كروس فيت وأيروبكس وتذاكر دخول يومية للصالات الرياضية',
    popular: true,
  },
  {
    id: 'yoga',
    name: 'يوغا وبيلاتس',
    nameEn: 'Yoga & Pilates',
    icon: '🧘',
    badgeColor: '#059669',
    defaultBookingType: 'session',
    defaultDuration: 60,
    unitName: 'جلسة',
    description: 'جلسات استرخاء وتأمل وبيلاتس ريفورمر مع مدربات محترفات',
    popular: false,
  },
  {
    id: 'martial_arts',
    name: 'فنون قتالية',
    nameEn: 'Martial Arts',
    icon: '🥋',
    badgeColor: '#B91C1C',
    defaultBookingType: 'session',
    defaultDuration: 60,
    unitName: 'حصة تدريبية',
    description: 'كيك بوكسينغ، كاراتيه، وفنون الدفاع عن النفس',
    popular: false,
  },
  {
    id: 'other',
    name: 'أنشطة أخرى',
    nameEn: 'Other Activities',
    icon: '🎯',
    badgeColor: '#6B7280',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'نشاط',
    description: 'أنشطة ترفيهية ورياضية متنوعة',
    popular: false,
  },
];

export const CITIES = [
  'كل المدن والمناطق',
  'القاهرة الجديدة',
  'الشيخ زايد',
  'المعادي',
  'مدينة نصر',
  'مصر الجديدة',
  'كفر الشيخ',
  'الإسكندرية',
  'طريق السويس',
  'أكتوبر',
];

export function getActivityMeta(activityId) {
  const found = ACTIVITIES.find((a) => a.id === activityId);
  if (found) return found;
  return {
    id: activityId || 'activity',
    name: activityId || 'نشاط رياضي',
    nameEn: activityId || 'Activity',
    icon: '🏆',
    badgeColor: '#0D6B4F',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    unitName: 'حجز',
  };
}
